# Generated by Django 4.2.3 on 2023-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('answer', models.CharField(max_length=200, verbose_name='题目答案')),
                ('difficulty', models.IntegerField(verbose_name='题目难度')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('question_type', models.CharField(choices=[('S', '单项选择'), ('M', '多项选择'), ('F', '填空')], max_length=1, verbose_name='题目类型')),
            ],
        ),
    ]
