# Generated by Django 4.2.3 on 2023-07-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testAPP', '0005_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('answer', models.CharField(max_length=200, verbose_name='题目答案')),
                ('difficulty', models.CharField(choices=[('E', '简单'), ('M', '中等'), ('H', '困难')], max_length=1, verbose_name='题目难度')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('question_type', models.CharField(choices=[('S', '单项选择'), ('M', '多项选择'), ('F', '填空')], max_length=1, verbose_name='题目类型')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testAPP.question')),
            ],
        ),
    ]
