# Generated by Django 4.2.3 on 2023-07-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testAPP', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
