# Generated by Django 4.2.3 on 2023-08-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAPP', '0007_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='label',
            field=models.TextField(default='网络', verbose_name='题目分类'),
        ),
    ]
